### ISSUE TITLE
Refactor the Sidebar to be part of the view

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#303]
Each view should have its own sidebar. We shouldn't have one mega sidebar that is outside of each view, because communicating with that sidebar is non-trivial.

**Comment by wooferzfg** [comment]
I'm not sure how doable it is to move the sidebar into each view because `react-sidebar` requires the `Sidebar` class to wrap around everything else.

Could add a `renderSidebarContent` method to each view component instead and just call that from `LiveSplit.tsx`? I think that would still give us two-way communication with the sidebar.
