### ISSUE TITLE
What is the difference between the livesplit one website and loal host.

### ISSUE THREAD

**Issue by nimnim111** [LiveSplit/LiveSplitOne#495]
also how do i use the sockets feature

**Comment by CryZe** [comment]
There is no difference, they are the same. However it's easier to connect to a websocket server via http rather than https. So I guess in that sense it's easier if you have a local version. You'd need to write a websocket server and then send these commands to control LSO: https://github.com/LiveSplit/LiveSplitOne/blob/83780e6d51ba2190526966a3d686d8105f7e8680/src/ui/TimerView.tsx#L255-L266

**Comment by nimnim111** [comment]
is there a tutorial on how to that thank you btw
