### ISSUE TITLE
Font size and window resizing

### ISSUE THREAD

**Issue by GimmyTomas** [LiveSplit/LiveSplitOne#878]
Something changed in the appearance of LivesplitOne from last time I used it (a few days ago).

- On Safari (incognito mode) and Chrome, when a window resize forces the timer to change shape, the font size becomes permanently bigger until refresh (see video below).
- On Safari (not incognito mode), the change in font size remains after a refresh and the actions "stack" over time, possibly creating extremely large fonts (see image below).
- Even when no window resize is done, the default font size seems to be changed compared to a few days ago. For example, if I load my usual splits and layout on an incognito mode window, then my default OBS cropping settings don't work as well they used to do.
- 

https://github.com/LiveSplit/LiveSplitOne/assets/23743163/c453c699-0a31-4215-992b-51040531f3ed

<img width="1507" alt="Screenshot 2024-05-14 alle 20 17 09" src="https://github.com/LiveSplit/LiveSplitOne/assets/23743163/254d717f-843d-4bc6-917d-5bd78f0cc412">

**Comment by CryZe** [comment]
This seems to be because the "mobile layout" where the layout makes up the entire width overwrites the stored width, so when the window is larger again, it uses the much smaller width.

The reason why the layout in general looks different from before is because we completely changed the entire layout rendering to match the desktop versions of LiveSplit One.

@wooferzfg I'm on a business trip for a few days. The former is probably an easy fix where the mobile layout should probably not mess with the stored width / height at all.
